#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    securityalarmgateway-app:
        image: securityalarmgateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://securityalarmgateway-postgresql:5432/securityalarmgateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=securityalarmgateway-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    securityalarmgateway-postgresql:
        extends:
            file: postgresql.yml
            service: securityalarmgateway-postgresql
    # Uncomment to have Cassandra working with the gateway
    # securityalarmgateway-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: securityalarmgateway-cassandra
    # securityalarmgateway-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: securityalarmgateway-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
